package INTERFAZ;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/CODIGO/lexer.flex

import CODIGO.*;
import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\2\2\1\22\0\1\3\1\4\1\0"+
    "\1\5\2\4\1\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\1\14\1\15\1\16\12\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\4\1\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\6\33\1\34\1\35\3\33\1\36\1\37"+
    "\1\40\1\33\1\41\4\33\4\0\1\4\1\0\1\42"+
    "\1\43\1\44\1\45\1\46\1\33\1\47\1\33\1\50"+
    "\1\51\1\33\1\52\1\53\1\54\1\55\1\56\1\33"+
    "\1\57\1\60\1\61\1\62\1\63\3\33\1\64\1\65"+
    "\1\66\1\67\7\0\1\2\33\0\1\4\35\0\1\4"+
    "\u0168\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\1\1\13\1\1\1\14"+
    "\1\15\1\16\1\17\15\20\1\21\1\2\1\22\1\23"+
    "\1\0\1\23\1\24\1\0\1\23\1\25\2\0\1\26"+
    "\2\0\1\27\1\30\1\31\2\32\1\13\1\27\1\33"+
    "\23\20\1\0\2\34\2\35\1\0\1\36\1\0\1\37"+
    "\25\20\1\23\1\40\1\41\20\20\1\42\7\20\1\43"+
    "\10\20\1\44\3\20\1\45\1\46\1\20\1\47\1\50"+
    "\1\51\4\20\1\52\1\53\1\54\3\20\1\55\2\20"+
    "\1\56\1\20\1\57\1\60\1\61\4\20\1\62\6\20"+
    "\1\63\1\64\1\20\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\160\0\250\0\340\0\u0118\0\160"+
    "\0\160\0\u0150\0\160\0\u0150\0\u0188\0\u01c0\0\u0150\0\160"+
    "\0\u0150\0\160\0\u0150\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\160\0\160\0\160\0\u04d0\0\u0508\0\u0508\0\u0540\0\u0578"+
    "\0\u0578\0\u05b0\0\u05e8\0\u0620\0\70\0\u0658\0\u0690\0\u06c8"+
    "\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888"+
    "\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08"+
    "\0\u0c40\0\u0c78\0\u0cb0\0\u0508\0\u0ce8\0\u0578\0\u0d20\0\u0d58"+
    "\0\70\0\u0d90\0\u07a8\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8"+
    "\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u1228"+
    "\0\u0cb0\0\70\0\u0348\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340"+
    "\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500"+
    "\0\u1538\0\u1570\0\u15a8\0\u0348\0\u15e0\0\u1618\0\u1650\0\u1688"+
    "\0\u16c0\0\u16f8\0\u1730\0\u0348\0\u1768\0\u17a0\0\u17d8\0\u1810"+
    "\0\u1848\0\u1880\0\u18b8\0\u18f0\0\u0348\0\u1928\0\u1960\0\u1998"+
    "\0\u0348\0\u0348\0\u19d0\0\u0348\0\u0348\0\u0348\0\u1a08\0\u1a40"+
    "\0\u1a78\0\u1ab0\0\u0348\0\u0348\0\u0348\0\u1ae8\0\u1b20\0\u1b58"+
    "\0\u0348\0\u1b90\0\u1bc8\0\u0348\0\u1c00\0\u0348\0\u0348\0\u0348"+
    "\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0\0\u0348\0\u1d18\0\u1d50\0\u1d88"+
    "\0\u1dc0\0\u1df8\0\u1e30\0\u0348\0\u0348\0\u1e68\0\u0348\0\u0348";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\4\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\23\32\1\41\1\42\1\43\107\0\1\44"+
    "\54\0\3\45\1\0\7\45\1\46\1\45\1\0\3\45"+
    "\40\47\3\45\4\0\3\50\1\0\7\50\1\51\1\50"+
    "\1\0\3\50\40\52\3\50\1\0\1\53\1\0\1\53"+
    "\3\54\1\55\7\54\1\56\5\54\40\56\1\54\1\57"+
    "\1\54\17\0\1\44\5\0\40\60\20\0\1\61\1\0"+
    "\1\62\5\0\40\60\7\0\3\63\1\0\5\63\1\64"+
    "\1\63\1\65\1\63\1\0\3\63\40\66\3\63\5\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\37\32\1\70\10\0\2\67"+
    "\3\0\1\67\1\0\2\67\1\0\1\32\1\67\1\0"+
    "\1\67\1\0\1\67\25\32\1\71\12\32\10\0\2\67"+
    "\3\0\1\67\1\0\2\67\1\0\1\32\1\67\1\0"+
    "\1\67\1\0\1\67\15\32\1\72\5\32\1\73\4\32"+
    "\1\74\4\32\1\75\2\32\10\0\2\67\3\0\1\67"+
    "\1\0\2\67\1\0\1\32\1\67\1\0\1\67\1\0"+
    "\1\67\21\32\1\76\1\32\1\77\14\32\10\0\2\67"+
    "\3\0\1\67\1\0\2\67\1\0\1\32\1\67\1\0"+
    "\1\67\1\0\1\67\27\32\1\100\10\32\10\0\2\67"+
    "\3\0\1\67\1\0\2\67\1\0\1\32\1\67\1\0"+
    "\1\67\1\0\1\67\23\32\1\101\14\32\10\0\2\67"+
    "\3\0\1\67\1\0\2\67\1\0\1\32\1\67\1\0"+
    "\1\67\1\0\1\67\40\32\10\0\2\67\3\0\1\67"+
    "\1\0\2\67\1\0\1\32\1\67\1\0\1\67\1\0"+
    "\1\67\21\32\1\102\6\32\1\103\4\32\1\104\2\32"+
    "\10\0\2\67\3\0\1\67\1\0\2\67\1\0\1\32"+
    "\1\67\1\0\1\67\1\0\1\67\21\32\1\105\16\32"+
    "\10\0\2\67\3\0\1\67\1\0\2\67\1\0\1\32"+
    "\1\67\1\0\1\67\1\0\1\67\21\32\1\106\6\32"+
    "\1\107\7\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\35\32"+
    "\1\110\2\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\32\32"+
    "\1\111\5\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\21\32"+
    "\1\112\16\32\20\0\1\113\1\0\1\44\54\0\3\114"+
    "\1\0\11\114\1\0\46\114\4\0\3\115\3\0\1\115"+
    "\1\0\3\115\1\47\1\115\1\0\1\115\1\0\1\115"+
    "\40\47\1\0\1\115\5\0\3\116\1\0\11\116\1\0"+
    "\46\116\4\0\3\117\3\0\1\117\1\0\3\117\1\52"+
    "\1\117\1\0\1\117\1\0\1\117\40\52\1\0\1\117"+
    "\2\0\1\53\1\0\1\53\3\0\1\55\56\0\1\53"+
    "\4\0\4\120\1\0\60\120\3\0\1\56\1\120\2\56"+
    "\1\121\56\56\1\120\1\56\1\0\1\53\1\0\1\122"+
    "\3\120\1\55\56\120\1\122\1\120\17\0\1\60\5\0"+
    "\40\60\20\0\1\61\1\0\1\61\65\0\1\61\1\0"+
    "\1\62\54\0\3\63\1\0\11\63\1\0\46\63\4\0"+
    "\3\63\1\0\7\63\1\123\1\63\1\0\46\63\4\0"+
    "\3\63\1\0\5\63\1\64\1\63\1\65\1\63\1\0"+
    "\46\63\4\0\3\63\1\0\7\63\1\66\1\63\1\0"+
    "\3\63\40\66\3\63\5\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\2\67\1\0\1\67\1\0\41\67\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\35\32\1\124\2\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\15\32\1\125\22\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\20\32\1\126\17\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\32\32\1\127\5\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\25\32\1\130\12\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\15\32\1\131\22\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\17\32\1\132\20\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\36\32\1\133\1\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\34\32\1\134\3\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\22\32\1\135\15\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\34\32\1\136\3\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\33\32\1\137\4\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\25\32\1\140\12\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\22\32\1\141\15\32\10\0"+
    "\2\67\3\0\1\67\1\0\2\67\1\0\1\32\1\67"+
    "\1\0\1\67\1\0\1\67\17\32\1\142\13\32\1\143"+
    "\4\32\10\0\2\67\3\0\1\67\1\0\2\67\1\0"+
    "\1\32\1\67\1\0\1\67\1\0\1\67\24\32\1\144"+
    "\1\32\1\145\11\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\26\32\1\146\11\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\23\32\1\147\14\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\150\5\32\22\0\1\151\54\0\3\115\3\0"+
    "\1\115\1\0\5\115\1\0\1\115\1\0\41\115\1\0"+
    "\1\115\5\0\3\117\3\0\1\117\1\0\5\117\1\0"+
    "\1\117\1\0\41\117\1\0\1\117\4\0\4\120\1\152"+
    "\60\120\1\0\1\53\1\0\1\122\3\120\1\152\56\120"+
    "\1\122\1\120\5\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\25\32"+
    "\1\153\12\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\27\32"+
    "\1\154\10\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\21\32"+
    "\1\155\16\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\17\32"+
    "\1\156\20\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\30\32"+
    "\1\157\7\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\20\32"+
    "\1\160\17\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\23\32"+
    "\1\161\14\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\23\32"+
    "\1\162\14\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\21\32"+
    "\1\163\16\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\35\32"+
    "\1\164\2\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\30\32"+
    "\1\165\7\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\34\32"+
    "\1\166\3\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\34\32"+
    "\1\167\3\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\32\32"+
    "\1\170\5\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\34\32"+
    "\1\171\3\32\10\0\2\67\3\0\1\67\1\0\2\67"+
    "\1\0\1\32\1\67\1\0\1\67\1\0\1\67\34\32"+
    "\1\172\1\173\2\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\174\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\16\32\1\175\21\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\176\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\177\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\20\32\1\200\17\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\17\32\1\201\20\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\27\32\1\202\10\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\35\32\1\203\2\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\204\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\205\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\26\32\1\206\11\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\20\32\1\207\17\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\210\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\211\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\20\32\1\212\17\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\213\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\23\32\1\214\14\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\215\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\216\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\217\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\220\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\221\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\222\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\27\32\1\223\10\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\21\32\1\224\16\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\225\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\226\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\227\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\230\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\231\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\23\32\1\232\14\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\233\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\234\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\235\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\236\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\31\32\1\237\6\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\27\32\1\240\10\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\241\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\34\32\1\242\3\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\22\32\1\243\15\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\244\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\20\32\1\245\17\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\246\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\247\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\250\5\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\251\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\22\32\1\252\15\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\253\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\35\32\1\254\2\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\255\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\23\32\1\256\14\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\35\32\1\257\2\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\20\32\1\260\17\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\261\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\17\32\1\262\20\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\25\32\1\263\12\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\264\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\265\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\15\32\1\266\22\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\30\32\1\267\7\32\10\0\2\67\3\0\1\67\1\0"+
    "\2\67\1\0\1\32\1\67\1\0\1\67\1\0\1\67"+
    "\32\32\1\270\5\32\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\41\1\1\0\2\1\1\0\2\1\2\0"+
    "\1\11\2\0\33\1\1\0\4\1\1\0\1\11\1\0"+
    "\27\1\1\11\116\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR_#", yyline, yycolumn);
            }
            // fall through
          case 55: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 56: break;
          case 3:
            { return token(yytext(), "ERROR_0", yyline, yycolumn);
            }
            // fall through
          case 57: break;
          case 4:
            { return token(yytext(), "ERROR_6", yyline, yycolumn);
            }
            // fall through
          case 58: break;
          case 5:
            { return token(yytext(), "ERROR_8", yyline, yycolumn);
            }
            // fall through
          case 59: break;
          case 6:
            { return token(yytext(), "Signo_De_Agrupacion_1", yyline, yycolumn);
            }
            // fall through
          case 60: break;
          case 7:
            { return token(yytext(), "Signo_De_Agrupacion_2", yyline, yycolumn);
            }
            // fall through
          case 61: break;
          case 8:
            { return token(yytext(), "Operador_Aritmetico_Mas", yyline, yycolumn);
            }
            // fall through
          case 62: break;
          case 9:
            { return token(yytext(), "Separador", yyline, yycolumn);
            }
            // fall through
          case 63: break;
          case 10:
            { return token(yytext(), "Operador_Aritmetico_Menos", yyline, yycolumn);
            }
            // fall through
          case 64: break;
          case 11:
            { return token(yytext(), "Numero_Entero", yyline, yycolumn);
            }
            // fall through
          case 65: break;
          case 12:
            { return token(yytext(), "Delimitador_De_Sentencia", yyline, yycolumn);
            }
            // fall through
          case 66: break;
          case 13:
            { return token(yytext(), "Signo_De_Agrupacion_3", yyline, yycolumn);
            }
            // fall through
          case 67: break;
          case 14:
            { return token(yytext(), "Operador_De_Asignacion", yyline, yycolumn);
            }
            // fall through
          case 68: break;
          case 15:
            { return token(yytext(), "Signo_De_Agrupacion_4", yyline, yycolumn);
            }
            // fall through
          case 69: break;
          case 16:
            { return token(yytext(), "Identificador_Variable", yyline, yycolumn);
            }
            // fall through
          case 70: break;
          case 17:
            { return token(yytext(), "Signo_De_Agrupacion_5", yyline, yycolumn);
            }
            // fall through
          case 71: break;
          case 18:
            { return token(yytext(), "Signo_De_Agrupacion_6", yyline, yycolumn);
            }
            // fall through
          case 72: break;
          case 19:
            { return token(yytext(), "ERROR_13", yyline, yycolumn);
            }
            // fall through
          case 73: break;
          case 20:
            { return token(yytext(), "Identificador_Resultado", yyline, yycolumn);
            }
            // fall through
          case 74: break;
          case 21:
            { return token(yytext(), "Identificador_Metodo", yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 22:
            { return token(yytext(), "ERROR_4", yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 23:
            { return token(yytext(), "ERROR_1", yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 24:
            { return token(yytext(), "ERROR_12", yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 25:
            { return token(yytext(), "ERROR_11", yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 26:
            { return token(yytext(), "ERROR_9", yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 27:
            { return token(yytext(), "ERROR_2", yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 28:
            { return token(yytext(), "ERROR_5", yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 29:
            { return token(yytext(), "ERROR_7", yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 30:
            { return token(yytext(), "Identificador_Cadena", yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 31:
            { return token(yytext(), "Numero_Decimal", yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 32:
            { return token(yytext(), "ERROR_3", yyline, yycolumn);
            }
            // fall through
          case 86: break;
          case 33:
            { return token(yytext(), "Palabra_Reservada_13", yyline, yycolumn);
            }
            // fall through
          case 87: break;
          case 34:
            { return token(yytext(), "Palabra_Reservada_12", yyline, yycolumn);
            }
            // fall through
          case 88: break;
          case 35:
            { return token(yytext(), "Palabra_Reservada_11", yyline, yycolumn);
            }
            // fall through
          case 89: break;
          case 36:
            { return token(yytext(), "Palabra_Reservada_16", yyline, yycolumn);
            }
            // fall through
          case 90: break;
          case 37:
            { return token(yytext(), "Palabra_Reservada_20", yyline, yycolumn);
            }
            // fall through
          case 91: break;
          case 38:
            { return token(yytext(), "Palabra_Reservada_1", yyline, yycolumn);
            }
            // fall through
          case 92: break;
          case 39:
            { return token(yytext(), "Palabra_Reservada_14", yyline, yycolumn);
            }
            // fall through
          case 93: break;
          case 40:
            { return token(yytext(), "Palabra_Reservada_15", yyline, yycolumn);
            }
            // fall through
          case 94: break;
          case 41:
            { return token(yytext(), "Palabra_Reservada_9", yyline, yycolumn);
            }
            // fall through
          case 95: break;
          case 42:
            { return token(yytext(), "Palabra_Reservada_6", yyline, yycolumn);
            }
            // fall through
          case 96: break;
          case 43:
            { return token(yytext(), "Palabra_Reservada_10", yyline, yycolumn);
            }
            // fall through
          case 97: break;
          case 44:
            { return token(yytext(), "Palabra_Reservada_22", yyline, yycolumn);
            }
            // fall through
          case 98: break;
          case 45:
            { return token(yytext(), "Palabra_Reservada_2", yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 46:
            { return token(yytext(), "Palabra_Reservada_21", yyline, yycolumn);
            }
            // fall through
          case 100: break;
          case 47:
            { return token(yytext(), "Palabra_Reservada_7", yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 48:
            { return token(yytext(), "Palabra_Reservada_3", yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 49:
            { return token(yytext(), "Palabra_Reservada_5", yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 50:
            { return token(yytext(), "Palabra_Reservada_17", yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 51:
            { return token(yytext(), "Palabra_Reservada_8", yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 52:
            { return token(yytext(), "Palabra_Reservada_18", yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 53:
            { return token(yytext(), "Palabra_Reservada_19", yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 54:
            { return token(yytext(), "Palabra_Reservada_4", yyline, yycolumn);
            }
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
